services:
    mongo:
        image: mongo:4.4.4
        container_name: mongo
        restart: always
        env_file:
            - ./envs/.mongo.env
        ports:
            -   "27017:27017"
        volumes:
            - mongodb:/data/db

    rmq:
        image: rabbitmq:4.0.5-management
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"

volumes:
    mongodb:
