version: '3.9'

services:
    mongo:
        image: mongo:4.4.4
        container_name: mongo
        restart: always
        env_file:
            - ./envs/.mongo.env
        ports:
            -   "27017:27017"
        volumes:
            - mongodb:/data/db

volumes:
    mongodb:
